## For more details on how to configure your build environment visit
# http://www.gradle.org/docs/current/userguide/build_environment.html
#
# Specifies the JVM arguments used for the daemon process.
# The setting is particularly useful for tweaking memory settings.
# Default value: -Xmx1024m -XX:MaxPermSize=256m
# org.gradle.jvmargs=-Xmx2048m -XX:MaxPermSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
#
# When configured, Gradle will run in incubating parallel mode.
# This option should only be used with decoupled projects. For more details, visit
# https://developer.android.com/r/tools/gradle-multi-project-decoupled-projects
# org.gradle.parallel=true
#Sun May 17 22:55:34 IST 2026
android.dependency.useConstraints=false
android.nonTransitiveRClass=true
android.r8.strictFullModeForKeepRules=false
android.uniquePackageNames=false
android.useAndroidX=true
kotlin.code.style=official
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.configuration-cache.problems=warn
org.gradle.jvmargs=-Xmx4096M -Dfile.encoding\=UTF-8 -XX\:+HeapDumpOnOutOfMemoryError -Dkotlin.daemon.jvm.options\="-Xmx4096M"
org.gradle.parallel=true

# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
android.disallowKotlinSourceSets=false
